# -*- coding: utf-8 -*-
"""FetchingAPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H41oKzdtOMlNgxdbg-bwSjTe0DNODG-I
"""

import csv
from datetime import datetime
import requests
from bs4 import BeautifulSoup

response = requests.get('https://in.indeed.com/jobs?q=front+end+developer&l=Bangalore%2C+Karnataka')
soup = BeautifulSoup(response.text, 'html.parser')
detail_employs = soup.find_all('div', 'job_seen_beacon')


def get_record(detail_employ):
    anchor_tag = detail_employ.h2.span
    job_title = anchor_tag.get('title')
    job_company_name = detail_employ.find('span', {'class': 'companyName'}).text
    job_location = detail_employ.find('div', {'class': 'companyLocation'}).text
    try:
        job_salary = detail_employ.find('span', {'class': 'salary-snippet'}).text.strip()
    except AttributeError:
        job_salary = "Salary Not Mentioned"
    job_details = detail_employ.find('div', {'class': 'job-snippet'}).text.strip()
    job_date = detail_employ.find('span', {'class': 'date'}).text
    today_date = datetime.today().strftime('%d-%m-%y').strip()

    record = (job_title, job_company_name, job_location, job_salary, job_details, job_date, today_date)
    return record

records = []
for detail_employ in detail_employs:
    record = get_record(detail_employ)
    records.append(record)

while True:
    try:
        url = 'https://in.indeed.com/' + soup.find('a', {'aria-label': 'Next'}).get('href')
    except AttributeError:
        break

    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    detail_employs = soup.find_all('div', 'job_seen_beacon')

    for detail_employ in detail_employs:
        record = get_record(detail_employ)
        records.append(record)
    print(len(records))

with open('results.csv', 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(['job_title', 'job_company_name', 'job_location', 'job_salary', 'job_details', 'job_date', 'today_date'])
            writer.writerows(records)

